#!/bin/bash
set -e

 # The custom entrypoint is used to generate the config file from environment variables with envsubst.

# Commented out because we have no config files right now. 
#echo "generating configuration files"
#FILES=/tmp/config/*
#for f in $FILES
#do
#  c=$(basename $f .tmp)
#  echo "... $c"
#  envsubst < $f > /usr/src/app/config/${c}
#done

echo "starting $@"
exec "$@"